version: '3'
services:
    chatbot:
        image: 7940image
        environment:
            ACCESS_TOKEN: 5851381047:AAEMNUka4JJcLLxTtvqGIvavCFupkHaWZ5E
            HOST: redis-16541.c253.us-central1-1.gce.cloud.redislabs.com
            PASSWORD: pQROReXe9oLSECAcqhAjdeAnEjzBL1ZO
            REDISPORT: 16541
        command: python chatbot.py